import Head from 'next/head';
import { Poppins } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import HeaderComponent from '@/components/Header';
import ScheduleNotifications from '@/components/ScheduleNotifications';

const inter = Poppins({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700'],
});

export interface UserProps {
  firstName: string;
  username: string;
  coinAmount: number;
  collectArea: string;
}

export default function Home() {
  const [loggedUser, setLoggedUser] = useState<UserProps>({
    firstName: 'Ricardo',
    username: 'ricardo.lemos',
    coinAmount: 3000,
    collectArea: 'SCR-1203',
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <HeaderComponent loggedUser={loggedUser} />
        <ScheduleNotifications
          scheduledDates={[
            { date: new Date('2023-05-01'), event: 'May Day' },
            { date: new Date('2023-06-21'), event: 'Summer Solstice' },
            { date: new Date('2023-12-25'), event: 'Christmas Day' },
          ]}
          loggedUser={loggedUser}
        />
      </main>
    </>
  );
}
