import Head from 'next/head';
import { Poppins } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import HeaderComponent from '@/components/Header';
import ScheduleNotifications from '@/components/ScheduleNotifications';
import { userMock } from '@/mock/user.mock';
import { User } from '@/types/User';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700'],
});

export default function Home() {
  const [loggedUser, setLoggedUser] = useState<User>(userMock);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${poppins.className}`}>
        <HeaderComponent loggedUser={loggedUser} />
        <ScheduleNotifications
          scheduledDates={[
            { date: new Date('2023-05-01'), event: 'May Day' },
            { date: new Date('2023-06-21'), event: 'Summer Solstice' },
            { date: new Date('2023-12-25'), event: 'Christmas Day' },
          ]}
          loggedUser={loggedUser}
        />
      </main>
    </>
  );
}
